Feature/details user
Antonio-Jr28/Onboarding-instituto-taqtile pull request #24
Opened 2023-01-31 20:34 UTC by Antonio-Jr28

Criando pagina de datalhes de usuario

2023-02-01 21:19 UTC, SamuelSsc requested changes
Me parece ter coisas de duas branchs/funcionalidades diferentes aqui(add-user e detail-user) ambos estão nesse mesmo pr.
provavelmente devido a algum conflito na hr do rebase??

2023-02-01 21:19 UTC, SamuelSsc commented on src/components/add/add-user.tsx
> +    function enviar(e: { preventDefault: () => void }) {
padrão do código em inglês.

2023-02-01 21:19 UTC, SamuelSsc commented on src/components/add/add-user.tsx
> +            <Container>
Essas duas Div's aninhadas não tem estilos, vc realmente precisa delas??

2023-02-01 21:19 UTC, SamuelSsc commented on src/components/list/list.tsx
> +  id: number | 'string';
pq vc adicionou tbm string? foi preciso??

2023-02-01 21:30 UTC, SamuelSsc commented on src/components/details/details-user.tsx
> +                <ListUser>Aniversario: {data?.user?.birthdaDate} </ListUser>
Typo: `birthDate`

2023-02-02 12:34 UTC, Antonio-Jr28 commented on src/components/add/add-user.tsx
> +            <Container>
preciso para ajustar elas

2023-02-02 14:05 UTC, SamuelSsc approved these changes

2023-02-02 14:06 UTC, merged